#!/bin/sh -f
cd /home/atsushi/work/jeda_release
cp /home/atsushi/work/jeda/src/vpp/vpp-1.2.tar.gz $1/src/vpp
cp /home/atsushi/work/jeda/src/jedapp/gcc-2.95.2.tar.gz $1/src/jedapp
cp /home/atsushi/work/jeda/src/readline/readline-4.2.tar.gz $1/src/readline
