#! /usr/bin/perl
#
#   perl gen_header.pl < ../runtime/exec_int_alu_ops.c > ../include/exec_int_alu_macro.h
#   perl gen_header.pl < ../runtime/exec_b_i_alu_ops.c > ../include/exec_b_i_alu_macro.h
#   perl gen_header.pl < ../runtime/exec_float_alu_ops.c > ../include/exec_float_alu_macro.h
#   perl gen_header.pl < ../runtime/code_exec.c > ../include/code_exec.h
#
#  
#  Copyright (C) 1999, 2000, 2001 Juniper Networks Inc.
#
#  This program is free software; you can redistribute it and/or modify it
#  under the terms of the GNU General Public License as published by the
#  Free Software Foundation; either version 2, or (at your option) any
#  later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307,
#   USA.  
#   

print "/********************************************/\n" ;
print "/* header generated by gen_header.pl        */\n" ;
print "/********************************************/\n" ;
while( <> ) {
  if( /^\s*void\s+(\w+)\s*\((.*)\)/ ) {
    $func_name = $1 ;
    $func_arg = $2 ;
  }
  if( /MACRO\s+(\w+)/ ) {
    $macro_name = $1 ;
    $R = $' ;
    if( $R =~ /^(\(\S+\))/ ) {
      $arg = $1 ;
      $carg = $1 ;
    }
    else {
      $arg = "" ;
      $carg = "()" ;
    }
    #print stderr "Got macro $macro_name\n" ;
    $line = <> ;
    chop $line ;
    $n = 0 ;
    while( !($line =~ /END MACRO/ ) ) {
      $line = <> ;
    }
    if( $func_name ne "" ) {
      print "void  $func_name($func_arg) ;\n" ;
    }
    $func_name = "" ;
  }
}
