%token <keyword> JD_ANDTILDA
%token <keyword> JD_TILDAAND
%token <keyword> JD_ORTILDA
%token <keyword> JD_TILDAOR
%token <keyword> JD_EORTILDA
%token <keyword> JD_TILDAEOR
%token <keyword> JD_LAND
%token <keyword> JD_LOR
%token <keyword> JD_RSHIFT
%token <keyword> JD_URSHIFT
%token <keyword> JD_LSHIFT
%token <keyword> JD_EQEQ
%token <keyword> JD_LE
%token <keyword> JD_GE
%token <keyword> JD_NE
%token <keyword> JD_EQEQEQ
%token <keyword> JD_NEQEQ
%token <keyword> JD_Q_EQ
%token <keyword> JD_Q_NEQ
%token <keyword> JD_QEQEQ
%token <keyword> JD_EQEQQ
%token <keyword> JD_C_EQEQ
%token <keyword> JD_D_PLUS
%token <keyword> JD_D_MINUS
%token <keyword> JD_D_AT
%token <keyword> JD_C_EQ
%token <keyword> JD_PLUS_EQ
%token <keyword> JD_MINUS_EQ
%token <keyword> JD_STAR_EQ
%token <keyword> JD_SLSH_EQ
%token <keyword> JD_MOD_EQ
%token <keyword> JD_LSHIFT_EQ
%token <keyword> JD_RSHIFT_EQ
%token <keyword> JD_URSHIFT_EQ
%token <keyword> JD_AND_EQ
%token <keyword> JD_OR_EQ
%token <keyword> JD_EOR_EQ
%token <keyword> JD_NAND_EQ
%token <keyword> JD_ANDN_EQ
%token <keyword> JD_NOR_EQ
%token <keyword> JD_ORN_EQ
%token <keyword> JD_NEOR_EQ
%token <keyword> JD_EORN_EQ
%token <keyword> '?'
%token <keyword> ':'
%token <keyword> '!'
%token <keyword> '%'
%token <keyword> '^'
%token <keyword> '&'
%token <keyword> '|'
%token <keyword> '+'
%token <keyword> '-'
%token <keyword> '<'
%token <keyword> '>'
%token <keyword> '='
%token <keyword> '*'
%token <keyword> '/'
%token <keyword> '.'
%token <keyword> '~'
%token <keyword> '@'
%token <keyword> '#'
%token <keyword> '$'
%token <keyword> '{'
%token <keyword> '}'
%token <keyword> '('
%token <keyword> ')'
%token <keyword> '['
%token <keyword> ']'
%token <keyword> '\''
