# Generated automatically from Makefile.in.in by configure.
# Makefile for program source directory in GNU NLS utilities package.
# Copyright (C) 1995, 1996, 1997 by Ulrich Drepper <drepper@gnu.ai.mit.edu>
#
# This file file be copied and used freely without restrictions.  It can
# be used in projects which are not available under the GNU Public License
# but which still want to provide support for the GNU gettext functionality.
# Please note that the actual code is *not* freely available.

PACKAGE = gcc
VERSION = 2.95.2

SHELL = /bin/sh


srcdir = ../../../gcc-2.95.2/gcc/po
top_srcdir = ../../../gcc-2.95.2/gcc
VPATH = ../../../gcc-2.95.2/gcc/po

prefix = /usr/local
exec_prefix = ${prefix}
datadir = $(prefix)/share
localedir = $(datadir)/locale
gnulocaledir = $(prefix)/share/locale
gettextsrcdir = $(prefix)/share/gettext/po
subdir = po

INSTALL = /usr/bin/ginstall -c
INSTALL_DATA = ${INSTALL} -m 644
MKINSTALLDIRS = $(top_srcdir)/../../gcc-2.95.2/gcc/../mkinstalldirs

CC = gcc
GENCAT = 
GMSGFMT = PATH=../src:$$PATH 
MSGFMT = 
XGETTEXT = PATH=../src:$$PATH AWK='gawk' $(SHELL) $(top_srcdir)/exgettext 
MSGMERGE = PATH=../src:$$PATH msgmerge

DEFS = -DHAVE_CONFIG_H
CFLAGS = -g -O2
CPPFLAGS = 

INCLUDES = -I.. -I$(top_srcdir)/intl

COMPILE = $(CC) -c $(DEFS) $(INCLUDES) $(CPPFLAGS) $(CFLAGS) $(XCFLAGS)

SOURCES = cat-id-tbl.c
POFILES =  en_UK.po
GMOFILES =  en_UK.gmo
DISTFILES = ChangeLog Makefile.in.in POTFILES.in $(PACKAGE).pot \
stamp-cat-id $(POFILES) $(GMOFILES) $(SOURCES)

POTFILES = \
	../../../gcc-2.95.2/gcc/acconfig.h \
	../../../gcc-2.95.2/gcc/assert.h \
	../../../gcc-2.95.2/gcc/basic-block.h \
	../../../gcc-2.95.2/gcc/bitmap.c \
	../../../gcc-2.95.2/gcc/bitmap.h \
	../../../gcc-2.95.2/gcc/c-aux-info.c \
	../../../gcc-2.95.2/gcc/c-common.c \
	../../../gcc-2.95.2/gcc/c-convert.c \
	../../../gcc-2.95.2/gcc/c-decl.c \
	../../../gcc-2.95.2/gcc/c-gperf.h \
	../../../gcc-2.95.2/gcc/c-iterate.c \
	../../../gcc-2.95.2/gcc/c-lang.c \
	../../../gcc-2.95.2/gcc/c-lex.c \
	../../../gcc-2.95.2/gcc/c-lex.h \
	../../../gcc-2.95.2/gcc/c-parse.c \
	../../../gcc-2.95.2/gcc/c-parse.h \
	../../../gcc-2.95.2/gcc/c-pragma.c \
	../../../gcc-2.95.2/gcc/c-pragma.h \
	../../../gcc-2.95.2/gcc/c-tree.h \
	../../../gcc-2.95.2/gcc/c-typeck.c \
	../../../gcc-2.95.2/gcc/caller-save.c \
	../../../gcc-2.95.2/gcc/calls.c \
	../../../gcc-2.95.2/gcc/cccp.c \
	../../../gcc-2.95.2/gcc/cexp.c \
	../../../gcc-2.95.2/gcc/../libiberty/choose-temp.c \
	../../../gcc-2.95.2/gcc/collect2.c \
	../../../gcc-2.95.2/gcc/combine.c \
	../../../gcc-2.95.2/gcc/conditions.h \
	../../../gcc-2.95.2/gcc/config/a29k/a29k.c \
	../../../gcc-2.95.2/gcc/config/a29k/a29k.h \
	../../../gcc-2.95.2/gcc/config/a29k/udi.h \
	../../../gcc-2.95.2/gcc/config/a29k/unix.h \
	../../../gcc-2.95.2/gcc/config/a29k/vx29k.h \
	../../../gcc-2.95.2/gcc/config/a29k/xm-a29k.h \
	../../../gcc-2.95.2/gcc/config/alpha/alpha-interix.h \
	../../../gcc-2.95.2/gcc/config/alpha/alpha.c \
	../../../gcc-2.95.2/gcc/config/alpha/alpha.h \
	../../../gcc-2.95.2/gcc/config/alpha/alpha32.h \
	../../../gcc-2.95.2/gcc/config/alpha/elf.h \
	../../../gcc-2.95.2/gcc/config/alpha/linux-ecoff.h \
	../../../gcc-2.95.2/gcc/config/alpha/linux-elf.h \
	../../../gcc-2.95.2/gcc/config/alpha/linux.h \
	../../../gcc-2.95.2/gcc/config/alpha/netbsd-elf.h \
	../../../gcc-2.95.2/gcc/config/alpha/netbsd.h \
	../../../gcc-2.95.2/gcc/config/alpha/openbsd.h \
	../../../gcc-2.95.2/gcc/config/alpha/osf.h \
	../../../gcc-2.95.2/gcc/config/alpha/osf12.h \
	../../../gcc-2.95.2/gcc/config/alpha/osf2or3.h \
	../../../gcc-2.95.2/gcc/config/alpha/vms-tramp.asm \
	../../../gcc-2.95.2/gcc/config/alpha/vms.h \
	../../../gcc-2.95.2/gcc/config/alpha/vxworks.h \
	../../../gcc-2.95.2/gcc/config/alpha/win-nt.h \
	../../../gcc-2.95.2/gcc/config/alpha/xm-alpha-interix.h \
	../../../gcc-2.95.2/gcc/config/alpha/xm-alpha.h \
	../../../gcc-2.95.2/gcc/config/alpha/xm-openbsd.h \
	../../../gcc-2.95.2/gcc/config/alpha/xm-vms.h \
	../../../gcc-2.95.2/gcc/config/alpha/xm-winnt.h \
	../../../gcc-2.95.2/gcc/config/aoutos.h \
	../../../gcc-2.95.2/gcc/config/arc/arc.c \
	../../../gcc-2.95.2/gcc/config/arc/arc.h \
	../../../gcc-2.95.2/gcc/config/arc/initfini.c \
	../../../gcc-2.95.2/gcc/config/arc/xm-arc.h \
	../../../gcc-2.95.2/gcc/config/arm/aof.h \
	../../../gcc-2.95.2/gcc/config/arm/aout.h \
	../../../gcc-2.95.2/gcc/config/arm/arm.c \
	../../../gcc-2.95.2/gcc/config/arm/arm.h \
	../../../gcc-2.95.2/gcc/config/arm/coff.h \
	../../../gcc-2.95.2/gcc/config/arm/linux-gas.h \
	../../../gcc-2.95.2/gcc/config/arm/netbsd.h \
	../../../gcc-2.95.2/gcc/config/arm/riscix.h \
	../../../gcc-2.95.2/gcc/config/arm/riscix1-1.h \
	../../../gcc-2.95.2/gcc/config/arm/rix-gas.h \
	../../../gcc-2.95.2/gcc/config/arm/semi.h \
	../../../gcc-2.95.2/gcc/config/arm/semiaof.h \
	../../../gcc-2.95.2/gcc/config/arm/xm-arm.h \
	../../../gcc-2.95.2/gcc/config/clipper/clipper.c \
	../../../gcc-2.95.2/gcc/config/clipper/clipper.h \
	../../../gcc-2.95.2/gcc/config/clipper/clix.h \
	../../../gcc-2.95.2/gcc/config/clipper/xm-clix.h \
	../../../gcc-2.95.2/gcc/config/convex/convex.c \
	../../../gcc-2.95.2/gcc/config/convex/convex.h \
	../../../gcc-2.95.2/gcc/config/convex/xm-convex.h \
	../../../gcc-2.95.2/gcc/config/dbx.h \
	../../../gcc-2.95.2/gcc/config/dbxcoff.h \
	../../../gcc-2.95.2/gcc/config/dsp16xx/dsp16xx.c \
	../../../gcc-2.95.2/gcc/config/dsp16xx/dsp16xx.h \
	../../../gcc-2.95.2/gcc/config/dsp16xx/xm-dsp16xx.h \
	../../../gcc-2.95.2/gcc/config/elxsi/elxsi.c \
	../../../gcc-2.95.2/gcc/config/elxsi/elxsi.h \
	../../../gcc-2.95.2/gcc/config/elxsi/xm-elxsi.h \
	../../../gcc-2.95.2/gcc/config/float-i128.h \
	../../../gcc-2.95.2/gcc/config/float-i32.h \
	../../../gcc-2.95.2/gcc/config/float-i64.h \
	../../../gcc-2.95.2/gcc/config/float-sh.h \
	../../../gcc-2.95.2/gcc/config/float-vax.h \
	../../../gcc-2.95.2/gcc/config/fp-bit.c \
	../../../gcc-2.95.2/gcc/config/fx80/fx80.c \
	../../../gcc-2.95.2/gcc/config/fx80/fx80.h \
	../../../gcc-2.95.2/gcc/config/fx80/xm-fx80.h \
	../../../gcc-2.95.2/gcc/config/gmicro/gmicro.c \
	../../../gcc-2.95.2/gcc/config/gmicro/gmicro.h \
	../../../gcc-2.95.2/gcc/config/gnu.h \
	../../../gcc-2.95.2/gcc/config/gofast.h \
	../../../gcc-2.95.2/gcc/config/h8300/h8300.c \
	../../../gcc-2.95.2/gcc/config/h8300/h8300.h \
	../../../gcc-2.95.2/gcc/config/h8300/xm-h8300.h \
	../../../gcc-2.95.2/gcc/config/i370/i370.c \
	../../../gcc-2.95.2/gcc/config/i370/i370.h \
	../../../gcc-2.95.2/gcc/config/i370/xm-i370.h \
	../../../gcc-2.95.2/gcc/config/i386/aix386.h \
	../../../gcc-2.95.2/gcc/config/i386/aix386ng.h \
	../../../gcc-2.95.2/gcc/config/i386/att.h \
	../../../gcc-2.95.2/gcc/config/i386/bsd.h \
	../../../gcc-2.95.2/gcc/config/i386/bsd386.h \
	../../../gcc-2.95.2/gcc/config/i386/crtdll.h \
	../../../gcc-2.95.2/gcc/config/i386/cygwin.h \
	../../../gcc-2.95.2/gcc/config/i386/dgux.c \
	../../../gcc-2.95.2/gcc/config/i386/dgux.h \
	../../../gcc-2.95.2/gcc/config/i386/freebsd-elf.h \
	../../../gcc-2.95.2/gcc/config/i386/freebsd.h \
	../../../gcc-2.95.2/gcc/config/i386/gas.h \
	../../../gcc-2.95.2/gcc/config/i386/gmon-sol2.c \
	../../../gcc-2.95.2/gcc/config/i386/gnu.h \
	../../../gcc-2.95.2/gcc/config/i386/djgpp-rtems.h \
	../../../gcc-2.95.2/gcc/config/i386/djgpp.h \
	../../../gcc-2.95.2/gcc/config/i386/gstabs.h \
	../../../gcc-2.95.2/gcc/config/i386/i386-aout.h \
	../../../gcc-2.95.2/gcc/config/i386/i386-coff.h \
	../../../gcc-2.95.2/gcc/config/i386/i386.c \
	../../../gcc-2.95.2/gcc/config/i386/i386.h \
	../../../gcc-2.95.2/gcc/config/i386/isc.h \
	../../../gcc-2.95.2/gcc/config/i386/isccoff.h \
	../../../gcc-2.95.2/gcc/config/i386/iscdbx.h \
	../../../gcc-2.95.2/gcc/config/i386/linux-aout.h \
	../../../gcc-2.95.2/gcc/config/i386/linux-oldld.h \
	../../../gcc-2.95.2/gcc/config/i386/linux.h \
	../../../gcc-2.95.2/gcc/config/i386/lynx-ng.h \
	../../../gcc-2.95.2/gcc/config/i386/lynx.h \
	../../../gcc-2.95.2/gcc/config/i386/mach.h \
	../../../gcc-2.95.2/gcc/config/i386/mingw32.h \
	../../../gcc-2.95.2/gcc/config/i386/moss.h \
	../../../gcc-2.95.2/gcc/config/i386/netbsd.h \
	../../../gcc-2.95.2/gcc/config/i386/next.h \
	../../../gcc-2.95.2/gcc/config/i386/os2.h \
	../../../gcc-2.95.2/gcc/config/i386/osf1elf.h \
	../../../gcc-2.95.2/gcc/config/i386/osf1elfgdb.h \
	../../../gcc-2.95.2/gcc/config/i386/osfelf.h \
	../../../gcc-2.95.2/gcc/config/i386/osfrose.h \
	../../../gcc-2.95.2/gcc/config/i386/perform.h \
	../../../gcc-2.95.2/gcc/config/i386/ptx4-i.h \
	../../../gcc-2.95.2/gcc/config/i386/rtems.h \
	../../../gcc-2.95.2/gcc/config/i386/rtemself.h \
	../../../gcc-2.95.2/gcc/config/i386/sco.h \
	../../../gcc-2.95.2/gcc/config/i386/sco4.h \
	../../../gcc-2.95.2/gcc/config/i386/sco4dbx.h \
	../../../gcc-2.95.2/gcc/config/i386/sco5.h \
	../../../gcc-2.95.2/gcc/config/i386/scodbx.h \
	../../../gcc-2.95.2/gcc/config/i386/seq-gas.h \
	../../../gcc-2.95.2/gcc/config/i386/seq-sysv3.h \
	../../../gcc-2.95.2/gcc/config/i386/seq2-sysv3.h \
	../../../gcc-2.95.2/gcc/config/i386/sequent.h \
	../../../gcc-2.95.2/gcc/config/i386/sol2.h \
	../../../gcc-2.95.2/gcc/config/i386/sol2gas.h \
	../../../gcc-2.95.2/gcc/config/i386/sun.h \
	../../../gcc-2.95.2/gcc/config/i386/sun386.h \
	../../../gcc-2.95.2/gcc/config/i386/svr3dbx.h \
	../../../gcc-2.95.2/gcc/config/i386/svr3gas.h \
	../../../gcc-2.95.2/gcc/config/i386/sysv3.h \
	../../../gcc-2.95.2/gcc/config/i386/sysv4.h \
	../../../gcc-2.95.2/gcc/config/i386/unix.h \
	../../../gcc-2.95.2/gcc/config/i386/v3gas.h \
	../../../gcc-2.95.2/gcc/config/i386/vsta.h \
	../../../gcc-2.95.2/gcc/config/i386/win-nt.h \
	../../../gcc-2.95.2/gcc/config/i386/winnt.c \
	../../../gcc-2.95.2/gcc/config/i386/xm-aix.h \
	../../../gcc-2.95.2/gcc/config/i386/xm-cygwin.h \
	../../../gcc-2.95.2/gcc/config/i386/xm-dos.h \
	../../../gcc-2.95.2/gcc/config/i386/xm-djgpp.h \
	../../../gcc-2.95.2/gcc/config/i386/xm-i386.h \
	../../../gcc-2.95.2/gcc/config/i386/xm-isc.h \
	../../../gcc-2.95.2/gcc/config/i386/xm-lynx.h \
	../../../gcc-2.95.2/gcc/config/i386/xm-mingw32.h \
	../../../gcc-2.95.2/gcc/config/i386/xm-next.h \
	../../../gcc-2.95.2/gcc/config/i386/xm-os2.h \
	../../../gcc-2.95.2/gcc/config/i386/xm-osf.h \
	../../../gcc-2.95.2/gcc/config/i386/xm-osf1elf.h \
	../../../gcc-2.95.2/gcc/config/i386/xm-sco.h \
	../../../gcc-2.95.2/gcc/config/i386/xm-sco5.h \
	../../../gcc-2.95.2/gcc/config/i386/xm-sysv4.h \
	../../../gcc-2.95.2/gcc/config/i386/xm-vsta.h \
	../../../gcc-2.95.2/gcc/config/i860/bsd-gas.h \
	../../../gcc-2.95.2/gcc/config/i860/bsd.h \
	../../../gcc-2.95.2/gcc/config/i860/fx2800.h \
	../../../gcc-2.95.2/gcc/config/i860/i860.c \
	../../../gcc-2.95.2/gcc/config/i860/i860.h \
	../../../gcc-2.95.2/gcc/config/i860/mach.h \
	../../../gcc-2.95.2/gcc/config/i860/paragon.h \
	../../../gcc-2.95.2/gcc/config/i860/sysv3.h \
	../../../gcc-2.95.2/gcc/config/i860/sysv4.h \
	../../../gcc-2.95.2/gcc/config/i860/xm-i860.h \
	../../../gcc-2.95.2/gcc/config/i960/i960-coff.h \
	../../../gcc-2.95.2/gcc/config/i960/i960.c \
	../../../gcc-2.95.2/gcc/config/i960/i960.h \
	../../../gcc-2.95.2/gcc/config/i960/rtems.h \
	../../../gcc-2.95.2/gcc/config/i960/vx960-coff.h \
	../../../gcc-2.95.2/gcc/config/i960/vx960.h \
	../../../gcc-2.95.2/gcc/config/i960/xm-i960.h \
	../../../gcc-2.95.2/gcc/config/libgloss.h \
	../../../gcc-2.95.2/gcc/config/linux-aout.h \
	../../../gcc-2.95.2/gcc/config/linux.h \
	../../../gcc-2.95.2/gcc/config/lynx-ng.h \
	../../../gcc-2.95.2/gcc/config/lynx.h \
	../../../gcc-2.95.2/gcc/config/m32r/initfini.c \
	../../../gcc-2.95.2/gcc/config/m32r/m32r.c \
	../../../gcc-2.95.2/gcc/config/m32r/m32r.h \
	../../../gcc-2.95.2/gcc/config/m32r/xm-m32r.h \
	../../../gcc-2.95.2/gcc/config/m68k/a-ux.h \
	../../../gcc-2.95.2/gcc/config/m68k/altos3068.h \
	../../../gcc-2.95.2/gcc/config/m68k/amix.h \
	../../../gcc-2.95.2/gcc/config/m68k/apollo68.h \
	../../../gcc-2.95.2/gcc/config/m68k/atari.h \
	../../../gcc-2.95.2/gcc/config/m68k/aux-crt1.c \
	../../../gcc-2.95.2/gcc/config/m68k/aux-exit.c \
	../../../gcc-2.95.2/gcc/config/m68k/aux-mcount.c \
	../../../gcc-2.95.2/gcc/config/m68k/auxas.h \
	../../../gcc-2.95.2/gcc/config/m68k/auxgas.h \
	../../../gcc-2.95.2/gcc/config/m68k/auxgld.h \
	../../../gcc-2.95.2/gcc/config/m68k/auxld.h \
	../../../gcc-2.95.2/gcc/config/m68k/ccur-GAS.h \
	../../../gcc-2.95.2/gcc/config/m68k/coff.h \
	../../../gcc-2.95.2/gcc/config/m68k/crds.h \
	../../../gcc-2.95.2/gcc/config/m68k/ctix.h \
	../../../gcc-2.95.2/gcc/config/m68k/dpx2.h \
	../../../gcc-2.95.2/gcc/config/m68k/dpx2cdbx.h \
	../../../gcc-2.95.2/gcc/config/m68k/dpx2g.h \
	../../../gcc-2.95.2/gcc/config/m68k/fpgnulib.c \
	../../../gcc-2.95.2/gcc/config/m68k/hp2bsd.h \
	../../../gcc-2.95.2/gcc/config/m68k/hp310.h \
	../../../gcc-2.95.2/gcc/config/m68k/hp310g.h \
	../../../gcc-2.95.2/gcc/config/m68k/hp320.h \
	../../../gcc-2.95.2/gcc/config/m68k/hp320g.h \
	../../../gcc-2.95.2/gcc/config/m68k/hp3bsd.h \
	../../../gcc-2.95.2/gcc/config/m68k/hp3bsd44.h \
	../../../gcc-2.95.2/gcc/config/m68k/hpux7.h \
	../../../gcc-2.95.2/gcc/config/m68k/isi-nfp.h \
	../../../gcc-2.95.2/gcc/config/m68k/isi.h \
	../../../gcc-2.95.2/gcc/config/m68k/linux-aout.h \
	../../../gcc-2.95.2/gcc/config/m68k/linux.h \
	../../../gcc-2.95.2/gcc/config/m68k/lynx-ng.h \
	../../../gcc-2.95.2/gcc/config/m68k/lynx.h \
	../../../gcc-2.95.2/gcc/config/m68k/m68k-aout.h \
	../../../gcc-2.95.2/gcc/config/m68k/m68k-coff.h \
	../../../gcc-2.95.2/gcc/config/m68k/m68k-none.h \
	../../../gcc-2.95.2/gcc/config/m68k/m68k-psos.h \
	../../../gcc-2.95.2/gcc/config/m68k/m68k.c \
	../../../gcc-2.95.2/gcc/config/m68k/m68k.h \
	../../../gcc-2.95.2/gcc/config/m68k/m68kemb.h \
	../../../gcc-2.95.2/gcc/config/m68k/m68kv4.h \
	../../../gcc-2.95.2/gcc/config/m68k/mot3300.h \
	../../../gcc-2.95.2/gcc/config/m68k/netbsd.h \
	../../../gcc-2.95.2/gcc/config/m68k/news.h \
	../../../gcc-2.95.2/gcc/config/m68k/news3.h \
	../../../gcc-2.95.2/gcc/config/m68k/news3gas.h \
	../../../gcc-2.95.2/gcc/config/m68k/newsgas.h \
	../../../gcc-2.95.2/gcc/config/m68k/next.h \
	../../../gcc-2.95.2/gcc/config/m68k/next21.h \
	../../../gcc-2.95.2/gcc/config/m68k/pbb.h \
	../../../gcc-2.95.2/gcc/config/m68k/plexus.h \
	../../../gcc-2.95.2/gcc/config/m68k/rtems.h \
	../../../gcc-2.95.2/gcc/config/m68k/sgs.h \
	../../../gcc-2.95.2/gcc/config/m68k/sun2.h \
	../../../gcc-2.95.2/gcc/config/m68k/sun2o4.h \
	../../../gcc-2.95.2/gcc/config/m68k/sun3.h \
	../../../gcc-2.95.2/gcc/config/m68k/sun3mach.h \
	../../../gcc-2.95.2/gcc/config/m68k/sun3n.h \
	../../../gcc-2.95.2/gcc/config/m68k/sun3n3.h \
	../../../gcc-2.95.2/gcc/config/m68k/sun3o3.h \
	../../../gcc-2.95.2/gcc/config/m68k/tower-as.h \
	../../../gcc-2.95.2/gcc/config/m68k/tower.h \
	../../../gcc-2.95.2/gcc/config/m68k/vxm68k.h \
	../../../gcc-2.95.2/gcc/config/m68k/xm-3b1.h \
	../../../gcc-2.95.2/gcc/config/m68k/xm-atari.h \
	../../../gcc-2.95.2/gcc/config/m68k/xm-crds.h \
	../../../gcc-2.95.2/gcc/config/m68k/xm-lynx.h \
	../../../gcc-2.95.2/gcc/config/m68k/xm-m68k.h \
	../../../gcc-2.95.2/gcc/config/m68k/xm-mot3300.h \
	../../../gcc-2.95.2/gcc/config/m68k/xm-next.h \
	../../../gcc-2.95.2/gcc/config/m68k/xm-plexus.h \
	../../../gcc-2.95.2/gcc/config/m88k/dgux.h \
	../../../gcc-2.95.2/gcc/config/m88k/dguxbcs.h \
	../../../gcc-2.95.2/gcc/config/m88k/dolph.h \
	../../../gcc-2.95.2/gcc/config/m88k/luna.h \
	../../../gcc-2.95.2/gcc/config/m88k/m88k-aout.h \
	../../../gcc-2.95.2/gcc/config/m88k/m88k-coff.h \
	../../../gcc-2.95.2/gcc/config/m88k/m88k.c \
	../../../gcc-2.95.2/gcc/config/m88k/m88k.h \
	../../../gcc-2.95.2/gcc/config/m88k/sysv3.h \
	../../../gcc-2.95.2/gcc/config/m88k/sysv4.h \
	../../../gcc-2.95.2/gcc/config/m88k/tekXD88.h \
	../../../gcc-2.95.2/gcc/config/m88k/xm-m88k.h \
	../../../gcc-2.95.2/gcc/config/m88k/xm-sysv3.h \
	../../../gcc-2.95.2/gcc/config/mips/abi64.h \
	../../../gcc-2.95.2/gcc/config/mips/bsd-4.h \
	../../../gcc-2.95.2/gcc/config/mips/bsd-5.h \
	../../../gcc-2.95.2/gcc/config/mips/cross64.h \
	../../../gcc-2.95.2/gcc/config/mips/dec-bsd.h \
	../../../gcc-2.95.2/gcc/config/mips/dec-osf1.h \
	../../../gcc-2.95.2/gcc/config/mips/ecoff.h \
	../../../gcc-2.95.2/gcc/config/mips/ecoffl.h \
	../../../gcc-2.95.2/gcc/config/mips/elf.h \
	../../../gcc-2.95.2/gcc/config/mips/elf64.h \
	../../../gcc-2.95.2/gcc/config/mips/elfl.h \
	../../../gcc-2.95.2/gcc/config/mips/elfl64.h \
	../../../gcc-2.95.2/gcc/config/mips/elforion.h \
	../../../gcc-2.95.2/gcc/config/mips/gnu.h \
	../../../gcc-2.95.2/gcc/config/mips/iris3.h \
	../../../gcc-2.95.2/gcc/config/mips/iris4.h \
	../../../gcc-2.95.2/gcc/config/mips/iris4loser.h \
	../../../gcc-2.95.2/gcc/config/mips/iris5.h \
	../../../gcc-2.95.2/gcc/config/mips/iris5gas.h \
	../../../gcc-2.95.2/gcc/config/mips/iris6.h \
	../../../gcc-2.95.2/gcc/config/mips/mips-5.h \
	../../../gcc-2.95.2/gcc/config/mips/mips.c \
	../../../gcc-2.95.2/gcc/config/mips/mips.h \
	../../../gcc-2.95.2/gcc/config/mips/netbsd.h \
	../../../gcc-2.95.2/gcc/config/mips/news4.h \
	../../../gcc-2.95.2/gcc/config/mips/news5.h \
	../../../gcc-2.95.2/gcc/config/mips/osfrose.h \
	../../../gcc-2.95.2/gcc/config/mips/r3900.h \
	../../../gcc-2.95.2/gcc/config/mips/rtems64.h \
	../../../gcc-2.95.2/gcc/config/mips/sni-gas.h \
	../../../gcc-2.95.2/gcc/config/mips/sni-svr4.h \
	../../../gcc-2.95.2/gcc/config/mips/svr3-4.h \
	../../../gcc-2.95.2/gcc/config/mips/svr3-5.h \
	../../../gcc-2.95.2/gcc/config/mips/svr4-4.h \
	../../../gcc-2.95.2/gcc/config/mips/svr4-5.h \
	../../../gcc-2.95.2/gcc/config/mips/svr4-t.h \
	../../../gcc-2.95.2/gcc/config/mips/ultrix.h \
	../../../gcc-2.95.2/gcc/config/mips/xm-iris6.h \
	../../../gcc-2.95.2/gcc/config/mips/xm-mips.h \
	../../../gcc-2.95.2/gcc/config/mn10200/divmod.c \
	../../../gcc-2.95.2/gcc/config/mn10200/mn10200.c \
	../../../gcc-2.95.2/gcc/config/mn10200/mn10200.h \
	../../../gcc-2.95.2/gcc/config/mn10200/udivmod.c \
	../../../gcc-2.95.2/gcc/config/mn10200/udivmodsi4.c \
	../../../gcc-2.95.2/gcc/config/mn10200/xm-mn10200.h \
	../../../gcc-2.95.2/gcc/config/mn10300/mn10300.c \
	../../../gcc-2.95.2/gcc/config/mn10300/mn10300.h \
	../../../gcc-2.95.2/gcc/config/mn10300/xm-mn10300.h \
	../../../gcc-2.95.2/gcc/config/msdos/mklibgcc.c \
	../../../gcc-2.95.2/gcc/config/netbsd.h \
	../../../gcc-2.95.2/gcc/config/nextstep.c \
	../../../gcc-2.95.2/gcc/config/nextstep.h \
	../../../gcc-2.95.2/gcc/config/nextstep21.h \
	../../../gcc-2.95.2/gcc/config/ns32k/encore.h \
	../../../gcc-2.95.2/gcc/config/ns32k/genix.h \
	../../../gcc-2.95.2/gcc/config/ns32k/merlin.h \
	../../../gcc-2.95.2/gcc/config/ns32k/netbsd.h \
	../../../gcc-2.95.2/gcc/config/ns32k/ns32k.c \
	../../../gcc-2.95.2/gcc/config/ns32k/ns32k.h \
	../../../gcc-2.95.2/gcc/config/ns32k/pc532-mach.h \
	../../../gcc-2.95.2/gcc/config/ns32k/pc532-min.h \
	../../../gcc-2.95.2/gcc/config/ns32k/pc532.h \
	../../../gcc-2.95.2/gcc/config/ns32k/sequent.h \
	../../../gcc-2.95.2/gcc/config/ns32k/tek6000.h \
	../../../gcc-2.95.2/gcc/config/ns32k/tek6100.h \
	../../../gcc-2.95.2/gcc/config/ns32k/tek6200.h \
	../../../gcc-2.95.2/gcc/config/ns32k/xm-ns32k.h \
	../../../gcc-2.95.2/gcc/config/ns32k/xm-pc532-min.h \
	../../../gcc-2.95.2/gcc/config/pa/pa-gas.h \
	../../../gcc-2.95.2/gcc/config/pa/pa-hiux.h \
	../../../gcc-2.95.2/gcc/config/pa/pa-hpux.h \
	../../../gcc-2.95.2/gcc/config/pa/pa-hpux10.h \
	../../../gcc-2.95.2/gcc/config/pa/pa-hpux7.h \
	../../../gcc-2.95.2/gcc/config/pa/pa-hpux9.h \
	../../../gcc-2.95.2/gcc/config/pa/pa-oldas.h \
	../../../gcc-2.95.2/gcc/config/pa/pa-osf.h \
	../../../gcc-2.95.2/gcc/config/pa/pa-pro-end.h \
	../../../gcc-2.95.2/gcc/config/pa/pa-pro.h \
	../../../gcc-2.95.2/gcc/config/pa/pa.c \
	../../../gcc-2.95.2/gcc/config/pa/pa.h \
	../../../gcc-2.95.2/gcc/config/pa/pa1.h \
	../../../gcc-2.95.2/gcc/config/pa/rtems.h \
	../../../gcc-2.95.2/gcc/config/pa/xm-pa.h \
	../../../gcc-2.95.2/gcc/config/pa/xm-pahpux.h \
	../../../gcc-2.95.2/gcc/config/pa/xm-papro.h \
	../../../gcc-2.95.2/gcc/config/pdp11/pdp11.c \
	../../../gcc-2.95.2/gcc/config/pdp11/pdp11.h \
	../../../gcc-2.95.2/gcc/config/pdp11/xm-pdp11.h \
	../../../gcc-2.95.2/gcc/config/psos.h \
	../../../gcc-2.95.2/gcc/config/ptx4.h \
	../../../gcc-2.95.2/gcc/config/pyr/pyr.c \
	../../../gcc-2.95.2/gcc/config/pyr/pyr.h \
	../../../gcc-2.95.2/gcc/config/pyr/xm-pyr.h \
	../../../gcc-2.95.2/gcc/config/romp/romp.c \
	../../../gcc-2.95.2/gcc/config/romp/romp.h \
	../../../gcc-2.95.2/gcc/config/romp/xm-romp.h \
	../../../gcc-2.95.2/gcc/config/rs6000/aix31.h \
	../../../gcc-2.95.2/gcc/config/rs6000/aix3newas.h \
	../../../gcc-2.95.2/gcc/config/rs6000/aix41.h \
	../../../gcc-2.95.2/gcc/config/rs6000/cygwin.h \
	../../../gcc-2.95.2/gcc/config/rs6000/eabi-ctors.c \
	../../../gcc-2.95.2/gcc/config/rs6000/eabi.h \
	../../../gcc-2.95.2/gcc/config/rs6000/eabiaix.h \
	../../../gcc-2.95.2/gcc/config/rs6000/eabile.h \
	../../../gcc-2.95.2/gcc/config/rs6000/eabilesim.h \
	../../../gcc-2.95.2/gcc/config/rs6000/eabisim.h \
	../../../gcc-2.95.2/gcc/config/rs6000/linux.h \
	../../../gcc-2.95.2/gcc/config/rs6000/lynx.h \
	../../../gcc-2.95.2/gcc/config/rs6000/mach.h \
	../../../gcc-2.95.2/gcc/config/rs6000/netware.h \
	../../../gcc-2.95.2/gcc/config/rs6000/rs6000.c \
	../../../gcc-2.95.2/gcc/config/rs6000/rs6000.h \
	../../../gcc-2.95.2/gcc/config/rs6000/rtems.h \
	../../../gcc-2.95.2/gcc/config/rs6000/sol-c0.c \
	../../../gcc-2.95.2/gcc/config/rs6000/sol2.h \
	../../../gcc-2.95.2/gcc/config/rs6000/sysv4.h \
	../../../gcc-2.95.2/gcc/config/rs6000/sysv4le.h \
	../../../gcc-2.95.2/gcc/config/rs6000/vxppc.h \
	../../../gcc-2.95.2/gcc/config/rs6000/win-nt.h \
	../../../gcc-2.95.2/gcc/config/rs6000/xm-cygwin.h \
	../../../gcc-2.95.2/gcc/config/rs6000/xm-lynx.h \
	../../../gcc-2.95.2/gcc/config/rs6000/xm-mach.h \
	../../../gcc-2.95.2/gcc/config/rs6000/xm-rs6000.h \
	../../../gcc-2.95.2/gcc/config/rs6000/xm-sysv4.h \
	../../../gcc-2.95.2/gcc/config/sh/elf.h \
	../../../gcc-2.95.2/gcc/config/sh/rtems.h \
	../../../gcc-2.95.2/gcc/config/sh/sh.c \
	../../../gcc-2.95.2/gcc/config/sh/sh.h \
	../../../gcc-2.95.2/gcc/config/sh/xm-sh.h \
	../../../gcc-2.95.2/gcc/config/sparc/aout.h \
	../../../gcc-2.95.2/gcc/config/sparc/bsd.h \
	../../../gcc-2.95.2/gcc/config/sparc/elf.h \
	../../../gcc-2.95.2/gcc/config/sparc/gmon-sol2.c \
	../../../gcc-2.95.2/gcc/config/sparc/hal.h \
	../../../gcc-2.95.2/gcc/config/sparc/linux-aout.h \
	../../../gcc-2.95.2/gcc/config/sparc/linux.h \
	../../../gcc-2.95.2/gcc/config/sparc/linux64.h \
	../../../gcc-2.95.2/gcc/config/sparc/lite.h \
	../../../gcc-2.95.2/gcc/config/sparc/litecoff.h \
	../../../gcc-2.95.2/gcc/config/sparc/lynx-ng.h \
	../../../gcc-2.95.2/gcc/config/sparc/lynx.h \
	../../../gcc-2.95.2/gcc/config/sparc/netbsd.h \
	../../../gcc-2.95.2/gcc/config/sparc/pbd.h \
	../../../gcc-2.95.2/gcc/config/sparc/rtems.h \
	../../../gcc-2.95.2/gcc/config/sparc/sol2-sld.h \
	../../../gcc-2.95.2/gcc/config/sparc/sol2.h \
	../../../gcc-2.95.2/gcc/config/sparc/sp64-aout.h \
	../../../gcc-2.95.2/gcc/config/sparc/sp64-elf.h \
	../../../gcc-2.95.2/gcc/config/sparc/sparc.c \
	../../../gcc-2.95.2/gcc/config/sparc/sparc.h \
	../../../gcc-2.95.2/gcc/config/sparc/splet.h \
	../../../gcc-2.95.2/gcc/config/sparc/sun4gas.h \
	../../../gcc-2.95.2/gcc/config/sparc/sun4o3.h \
	../../../gcc-2.95.2/gcc/config/sparc/sunos4.h \
	../../../gcc-2.95.2/gcc/config/sparc/sysv4.h \
	../../../gcc-2.95.2/gcc/config/sparc/vxsim.h \
	../../../gcc-2.95.2/gcc/config/sparc/vxsparc.h \
	../../../gcc-2.95.2/gcc/config/sparc/xm-linux.h \
	../../../gcc-2.95.2/gcc/config/sparc/xm-lynx.h \
	../../../gcc-2.95.2/gcc/config/sparc/xm-sol2.h \
	../../../gcc-2.95.2/gcc/config/sparc/xm-sp64.h \
	../../../gcc-2.95.2/gcc/config/sparc/xm-sparc.h \
	../../../gcc-2.95.2/gcc/config/sparc/xm-sysv4.h \
	../../../gcc-2.95.2/gcc/config/spur/spur.c \
	../../../gcc-2.95.2/gcc/config/spur/spur.h \
	../../../gcc-2.95.2/gcc/config/spur/xm-spur.h \
	../../../gcc-2.95.2/gcc/config/svr3.h \
	../../../gcc-2.95.2/gcc/config/svr4.h \
	../../../gcc-2.95.2/gcc/config/tahoe/harris.h \
	../../../gcc-2.95.2/gcc/config/tahoe/tahoe.c \
	../../../gcc-2.95.2/gcc/config/tahoe/tahoe.h \
	../../../gcc-2.95.2/gcc/config/tahoe/xm-tahoe.h \
	../../../gcc-2.95.2/gcc/config/v850/v850.c \
	../../../gcc-2.95.2/gcc/config/v850/v850.h \
	../../../gcc-2.95.2/gcc/config/v850/xm-v850.h \
	../../../gcc-2.95.2/gcc/config/vax/netbsd.h \
	../../../gcc-2.95.2/gcc/config/vax/ultrix.h \
	../../../gcc-2.95.2/gcc/config/vax/vax.c \
	../../../gcc-2.95.2/gcc/config/vax/vax.h \
	../../../gcc-2.95.2/gcc/config/vax/vaxv.h \
	../../../gcc-2.95.2/gcc/config/vax/vms.h \
	../../../gcc-2.95.2/gcc/config/vax/xm-vax.h \
	../../../gcc-2.95.2/gcc/config/vax/xm-vms.h \
	../../../gcc-2.95.2/gcc/config/we32k/we32k.c \
	../../../gcc-2.95.2/gcc/config/we32k/we32k.h \
	../../../gcc-2.95.2/gcc/config/we32k/xm-we32k.h \
	../../../gcc-2.95.2/gcc/config/winnt/dirent.c \
	../../../gcc-2.95.2/gcc/config/winnt/dirent.h \
	../../../gcc-2.95.2/gcc/config/winnt/fixinc-nt.c \
	../../../gcc-2.95.2/gcc/config/winnt/ld.c \
	../../../gcc-2.95.2/gcc/config/winnt/mklibgcc.c \
	../../../gcc-2.95.2/gcc/config/winnt/oldnames.c \
	../../../gcc-2.95.2/gcc/config/winnt/spawnv.c \
	../../../gcc-2.95.2/gcc/config/winnt/win-nt.h \
	../../../gcc-2.95.2/gcc/config/winnt/xm-winnt.h \
	../../../gcc-2.95.2/gcc/config/xm-alloca.h \
	../../../gcc-2.95.2/gcc/config/xm-gnu.h \
	../../../gcc-2.95.2/gcc/config/xm-lynx.h \
	../../../gcc-2.95.2/gcc/config/xm-siglist.h \
	../../../gcc-2.95.2/gcc/config/xm-std32.h \
	../../../gcc-2.95.2/gcc/convert.c \
	../../../gcc-2.95.2/gcc/convert.h \
	../../../gcc-2.95.2/gcc/cp/call.c \
	../../../gcc-2.95.2/gcc/cp/class.c \
	../../../gcc-2.95.2/gcc/cp/cp-tree.h \
	../../../gcc-2.95.2/gcc/cp/cvt.c \
	../../../gcc-2.95.2/gcc/cp/decl.c \
	../../../gcc-2.95.2/gcc/cp/decl.h \
	../../../gcc-2.95.2/gcc/cp/decl2.c \
	../../../gcc-2.95.2/gcc/cp/errfn.c \
	../../../gcc-2.95.2/gcc/cp/error.c \
	../../../gcc-2.95.2/gcc/cp/except.c \
	../../../gcc-2.95.2/gcc/cp/expr.c \
	../../../gcc-2.95.2/gcc/cp/friend.c \
	../../../gcc-2.95.2/gcc/cp/g++spec.c \
	../../../gcc-2.95.2/gcc/cp/hash.h \
	../../../gcc-2.95.2/gcc/cp/inc/new.h \
	../../../gcc-2.95.2/gcc/cp/init.c \
	../../../gcc-2.95.2/gcc/cp/input.c \
	../../../gcc-2.95.2/gcc/cp/lang-options.h \
	../../../gcc-2.95.2/gcc/cp/lang-specs.h \
	../../../gcc-2.95.2/gcc/cp/lex.c \
	../../../gcc-2.95.2/gcc/cp/lex.h \
	../../../gcc-2.95.2/gcc/cp/method.c \
	../../../gcc-2.95.2/gcc/cp/parse.c \
	../../../gcc-2.95.2/gcc/cp/parse.h \
	../../../gcc-2.95.2/gcc/cp/pt.c \
	../../../gcc-2.95.2/gcc/cp/ptree.c \
	../../../gcc-2.95.2/gcc/cp/repo.c \
	../../../gcc-2.95.2/gcc/cp/rtti.c \
	../../../gcc-2.95.2/gcc/cp/search.c \
	../../../gcc-2.95.2/gcc/cp/sig.c \
	../../../gcc-2.95.2/gcc/cp/spew.c \
	../../../gcc-2.95.2/gcc/cp/tinfo.h \
	../../../gcc-2.95.2/gcc/cp/tree.c \
	../../../gcc-2.95.2/gcc/cp/typeck.c \
	../../../gcc-2.95.2/gcc/cp/typeck2.c \
	../../../gcc-2.95.2/gcc/cp/xref.c \
	../../../gcc-2.95.2/gcc/../libiberty/cplus-dem.c \
	../../../gcc-2.95.2/gcc/cppalloc.c \
	../../../gcc-2.95.2/gcc/cpperror.c \
	../../../gcc-2.95.2/gcc/cppexp.c \
	../../../gcc-2.95.2/gcc/cpphash.c \
	../../../gcc-2.95.2/gcc/cpphash.h \
	../../../gcc-2.95.2/gcc/cpplib.c \
	../../../gcc-2.95.2/gcc/cpplib.h \
	../../../gcc-2.95.2/gcc/cppmain.c \
	../../../gcc-2.95.2/gcc/cse.c \
	../../../gcc-2.95.2/gcc/dbxout.c \
	../../../gcc-2.95.2/gcc/dbxstclass.h \
	../../../gcc-2.95.2/gcc/defaults.h \
	../../../gcc-2.95.2/gcc/../include/demangle.h \
	../../../gcc-2.95.2/gcc/doschk.c \
	../../../gcc-2.95.2/gcc/dwarf.h \
	../../../gcc-2.95.2/gcc/dwarf2.h \
	../../../gcc-2.95.2/gcc/dwarf2out.c \
	../../../gcc-2.95.2/gcc/dwarfout.c \
	../../../gcc-2.95.2/gcc/emit-rtl.c \
	../../../gcc-2.95.2/gcc/except.c \
	../../../gcc-2.95.2/gcc/except.h \
	../../../gcc-2.95.2/gcc/explow.c \
	../../../gcc-2.95.2/gcc/expmed.c \
	../../../gcc-2.95.2/gcc/expr.c \
	../../../gcc-2.95.2/gcc/expr.h \
	../../../gcc-2.95.2/gcc/final.c \
	../../../gcc-2.95.2/gcc/flags.h \
	../../../gcc-2.95.2/gcc/floatlib.c \
	../../../gcc-2.95.2/gcc/flow.c \
	../../../gcc-2.95.2/gcc/fold-const.c \
	../../../gcc-2.95.2/gcc/fp-test.c \
	../../../gcc-2.95.2/gcc/frame.c \
	../../../gcc-2.95.2/gcc/function.c \
	../../../gcc-2.95.2/gcc/function.h \
	../../../gcc-2.95.2/gcc/gansidecl.h \
	../../../gcc-2.95.2/gcc/gcc.c \
	../../../gcc-2.95.2/gcc/gcov-io.h \
	../../../gcc-2.95.2/gcc/gcov.c \
	../../../gcc-2.95.2/gcc/../libiberty/getopt.c \
	../../../gcc-2.95.2/gcc/../include/getopt.h \
	../../../gcc-2.95.2/gcc/../libiberty/getopt1.c \
	../../../gcc-2.95.2/gcc/getpwd.c \
	../../../gcc-2.95.2/gcc/ginclude/iso646.h \
	../../../gcc-2.95.2/gcc/ginclude/math-3300.h \
	../../../gcc-2.95.2/gcc/ginclude/math-68881.h \
	../../../gcc-2.95.2/gcc/ginclude/ppc-asm.h \
	../../../gcc-2.95.2/gcc/ginclude/proto.h \
	../../../gcc-2.95.2/gcc/ginclude/stdarg.h \
	../../../gcc-2.95.2/gcc/ginclude/stdbool.h \
	../../../gcc-2.95.2/gcc/ginclude/stddef.h \
	../../../gcc-2.95.2/gcc/ginclude/va-alpha.h \
	../../../gcc-2.95.2/gcc/ginclude/va-arc.h \
	../../../gcc-2.95.2/gcc/ginclude/va-clipper.h \
	../../../gcc-2.95.2/gcc/ginclude/va-h8300.h \
	../../../gcc-2.95.2/gcc/ginclude/va-i860.h \
	../../../gcc-2.95.2/gcc/ginclude/va-i960.h \
	../../../gcc-2.95.2/gcc/ginclude/va-m32r.h \
	../../../gcc-2.95.2/gcc/ginclude/va-m88k.h \
	../../../gcc-2.95.2/gcc/ginclude/va-mips.h \
	../../../gcc-2.95.2/gcc/ginclude/va-mn10200.h \
	../../../gcc-2.95.2/gcc/ginclude/va-mn10300.h \
	../../../gcc-2.95.2/gcc/ginclude/va-pa.h \
	../../../gcc-2.95.2/gcc/ginclude/va-ppc.h \
	../../../gcc-2.95.2/gcc/ginclude/va-pyr.h \
	../../../gcc-2.95.2/gcc/ginclude/va-sh.h \
	../../../gcc-2.95.2/gcc/ginclude/va-sparc.h \
	../../../gcc-2.95.2/gcc/ginclude/va-spur.h \
	../../../gcc-2.95.2/gcc/ginclude/va-v850.h \
	../../../gcc-2.95.2/gcc/ginclude/varargs.h \
	../../../gcc-2.95.2/gcc/glimits.h \
	../../../gcc-2.95.2/gcc/global.c \
	../../../gcc-2.95.2/gcc/gmon.c \
	../../../gcc-2.95.2/gcc/gstab.h \
	../../../gcc-2.95.2/gcc/gsyms.h \
	../../../gcc-2.95.2/gcc/gsyslimits.h \
	../../../gcc-2.95.2/gcc/halfpic.c \
	../../../gcc-2.95.2/gcc/halfpic.h \
	../../../gcc-2.95.2/gcc/hard-reg-set.h \
	../../../gcc-2.95.2/gcc/input.h \
	../../../gcc-2.95.2/gcc/integrate.c \
	../../../gcc-2.95.2/gcc/integrate.h \
	../../../gcc-2.95.2/gcc/intl.c \
	../../../gcc-2.95.2/gcc/intl.h \
	../../../gcc-2.95.2/gcc/intl/bindtextdom.c \
	../../../gcc-2.95.2/gcc/intl/cat-compat.c \
	../../../gcc-2.95.2/gcc/intl/dcgettext.c \
	../../../gcc-2.95.2/gcc/intl/dgettext.c \
	../../../gcc-2.95.2/gcc/intl/explodename.c \
	../../../gcc-2.95.2/gcc/intl/finddomain.c \
	../../../gcc-2.95.2/gcc/intl/gettext.c \
	../../../gcc-2.95.2/gcc/intl/gettext.h \
	../../../gcc-2.95.2/gcc/intl/gettextP.h \
	../../../gcc-2.95.2/gcc/intl/hash-string.h \
	../../../gcc-2.95.2/gcc/intl/intl-compat.c \
	../../../gcc-2.95.2/gcc/intl/l10nflist.c \
	../../../gcc-2.95.2/gcc/intl/libgettext.h \
	../../../gcc-2.95.2/gcc/intl/loadinfo.h \
	../../../gcc-2.95.2/gcc/intl/loadmsgcat.c \
	../../../gcc-2.95.2/gcc/intl/localealias.c \
	../../../gcc-2.95.2/gcc/intl/textdomain.c \
	../../../gcc-2.95.2/gcc/jump.c \
	../../../gcc-2.95.2/gcc/limitx.h \
	../../../gcc-2.95.2/gcc/limity.h \
	../../../gcc-2.95.2/gcc/local-alloc.c \
	../../../gcc-2.95.2/gcc/loop.c \
	../../../gcc-2.95.2/gcc/loop.h \
	../../../gcc-2.95.2/gcc/machmode.h \
	../../../gcc-2.95.2/gcc/objc/objc-act.c \
	../../../gcc-2.95.2/gcc/objc/objc-act.h \
	../../../gcc-2.95.2/gcc/objc/objc-parse.c \
	../../../gcc-2.95.2/gcc/optabs.c \
	../../../gcc-2.95.2/gcc/output.h \
	../../../gcc-2.95.2/gcc/pcp.h \
	../../../gcc-2.95.2/gcc/../libiberty/pexecute.c \
	../../../gcc-2.95.2/gcc/prefix.c \
	../../../gcc-2.95.2/gcc/print-rtl.c \
	../../../gcc-2.95.2/gcc/print-tree.c \
	../../../gcc-2.95.2/gcc/profile.c \
	../../../gcc-2.95.2/gcc/protoize.c \
	../../../gcc-2.95.2/gcc/pself.c \
	../../../gcc-2.95.2/gcc/pself1.c \
	../../../gcc-2.95.2/gcc/pself2.c \
	../../../gcc-2.95.2/gcc/pself3.c \
	../../../gcc-2.95.2/gcc/real.c \
	../../../gcc-2.95.2/gcc/real.h \
	../../../gcc-2.95.2/gcc/recog.c \
	../../../gcc-2.95.2/gcc/recog.h \
	../../../gcc-2.95.2/gcc/reg-stack.c \
	../../../gcc-2.95.2/gcc/regclass.c \
	../../../gcc-2.95.2/gcc/regmove.c \
	../../../gcc-2.95.2/gcc/regs.h \
	../../../gcc-2.95.2/gcc/reload.c \
	../../../gcc-2.95.2/gcc/reload.h \
	../../../gcc-2.95.2/gcc/reload1.c \
	../../../gcc-2.95.2/gcc/reorg.c \
	../../../gcc-2.95.2/gcc/rtl.c \
	../../../gcc-2.95.2/gcc/rtl.h \
	../../../gcc-2.95.2/gcc/rtlanal.c \
	../../../gcc-2.95.2/gcc/scan.h \
	../../../gcc-2.95.2/gcc/sched.c \
	../../../gcc-2.95.2/gcc/sdbout.c \
	../../../gcc-2.95.2/gcc/stack.h \
	../../../gcc-2.95.2/gcc/stmt.c \
	../../../gcc-2.95.2/gcc/stor-layout.c \
	../../../gcc-2.95.2/gcc/stupid.c \
	../../../gcc-2.95.2/gcc/sys-protos.h \
	../../../gcc-2.95.2/gcc/sys-types.h \
	../../../gcc-2.95.2/gcc/toplev.c \
	../../../gcc-2.95.2/gcc/tree.c \
	../../../gcc-2.95.2/gcc/tree.h \
	../../../gcc-2.95.2/gcc/typeclass.h \
	../../../gcc-2.95.2/gcc/unprotoize.c \
	../../../gcc-2.95.2/gcc/unroll.c \
	../../../gcc-2.95.2/gcc/varasm.c \
	../../../gcc-2.95.2/gcc/version.c \
	../../../gcc-2.95.2/gcc/xcoffout.c \
	../../../gcc-2.95.2/gcc/xcoffout.h

CATALOGS = 
CATOBJEXT = 
INSTOBJEXT = 

.SUFFIXES:
.SUFFIXES: .c .o .po .pox .gmo .mo .msg .cat

.c.o:
	$(COMPILE) $<

.po.pox:
	$(MAKE) $(srcdir)/$(PACKAGE).pot
	$(MSGMERGE) $< $(srcdir)/$(PACKAGE).pot -o $*.pox

.po.mo:
	$(MSGFMT) -o $@ $<

.po.gmo:
	file=$(srcdir)/`echo $* | sed 's,.*/,,'`.gmo \
	  && rm -f $$file && $(GMSGFMT) -o $$file $<

.po.cat:
	sed -f ../intl/po2msg.sed < $< > $*.msg \
	  && rm -f $@ && $(GENCAT) $@ $*.msg


all: all-no

all-yes: $(srcdir)/cat-id-tbl.c $(CATALOGS)
all-no:

$(srcdir)/$(PACKAGE).pot: $(POTFILES)
	$(XGETTEXT) --default-domain=$(PACKAGE) --directory=$(top_srcdir) \
	  --add-comments --keyword=_ --keyword=N_ \
	  --files-from=$(srcdir)/POTFILES.in \
	&& test ! -f $(PACKAGE).po \
	   || ( rm -f $(srcdir)/$(PACKAGE).pot \
		&& mv $(PACKAGE).po $(srcdir)/$(PACKAGE).pot )

$(srcdir)/cat-id-tbl.c: $(srcdir)/stamp-cat-id; @:
$(srcdir)/stamp-cat-id: $(srcdir)/$(PACKAGE).pot
	rm -f cat-id-tbl.tmp
	sed -f ../intl/po2tbl.sed $(srcdir)/$(PACKAGE).pot \
		| sed -e "s/@PACKAGE NAME@/$(PACKAGE)/" > cat-id-tbl.tmp
	if cmp -s cat-id-tbl.tmp $(srcdir)/cat-id-tbl.c; then \
	  rm cat-id-tbl.tmp; \
	else \
	  echo cat-id-tbl.c changed; \
	  rm -f $(srcdir)/cat-id-tbl.c; \
	  mv cat-id-tbl.tmp $(srcdir)/cat-id-tbl.c; \
	fi
	cd $(srcdir) && rm -f stamp-cat-id && echo timestamp > stamp-cat-id


install: install-exec install-data
install-exec:
install-data: install-data-no
install-data-no: all
install-data-yes: all
	if test -r "$(MKINSTALLDIRS)"; then \
	  $(MKINSTALLDIRS) $(datadir); \
	else \
	  $(SHELL) $(top_srcdir)/mkinstalldirs $(datadir); \
	fi
	@catalogs='$(CATALOGS)'; \
	for cat in $$catalogs; do \
	  cat=`basename $$cat`; \
	  case "$$cat" in \
	    *.gmo) destdir=$(gnulocaledir);; \
	    *)     destdir=$(localedir);; \
	  esac; \
	  lang=`echo $$cat | sed 's/\$(CATOBJEXT)$$//'`; \
	  dir=$$destdir/$$lang/LC_MESSAGES; \
	  if test -r "$(MKINSTALLDIRS)"; then \
	    $(MKINSTALLDIRS) $$dir; \
	  else \
	    $(SHELL) $(top_srcdir)/mkinstalldirs $$dir; \
	  fi; \
	  if test -r $$cat; then \
	    $(INSTALL_DATA) $$cat $$dir/$(PACKAGE)$(INSTOBJEXT); \
	    echo "installing $$cat as $$dir/$(PACKAGE)$(INSTOBJEXT)"; \
	  else \
	    $(INSTALL_DATA) $(srcdir)/$$cat $$dir/$(PACKAGE)$(INSTOBJEXT); \
	    echo "installing $(srcdir)/$$cat as" \
		 "$$dir/$(PACKAGE)$(INSTOBJEXT)"; \
	  fi; \
	  if test -r $$cat.m; then \
	    $(INSTALL_DATA) $$cat.m $$dir/$(PACKAGE)$(INSTOBJEXT).m; \
	    echo "installing $$cat.m as $$dir/$(PACKAGE)$(INSTOBJEXT).m"; \
	  else \
	    if test -r $(srcdir)/$$cat.m ; then \
	      $(INSTALL_DATA) $(srcdir)/$$cat.m \
		$$dir/$(PACKAGE)$(INSTOBJEXT).m; \
	      echo "installing $(srcdir)/$$cat as" \
		   "$$dir/$(PACKAGE)$(INSTOBJEXT).m"; \
	    else \
	      true; \
	    fi; \
	  fi; \
	done
	if test "$(PACKAGE)" = "gettext"; then \
	  if test -r "$(MKINSTALLDIRS)"; then \
	    $(MKINSTALLDIRS) $(gettextsrcdir); \
	  else \
	    $(SHELL) $(top_srcdir)/mkinstalldirs $(gettextsrcdir); \
	  fi; \
	  $(INSTALL_DATA) $(srcdir)/Makefile.in.in \
			  $(gettextsrcdir)/Makefile.in.in; \
	else \
	  : ; \
	fi

# Define this as empty until I found a useful application.
installcheck:

uninstall:
	catalogs='$(CATALOGS)'; \
	for cat in $$catalogs; do \
	  cat=`basename $$cat`; \
	  lang=`echo $$cat | sed 's/\$(CATOBJEXT)$$//'`; \
	  rm -f $(localedir)/$$lang/LC_MESSAGES/$(PACKAGE)$(INSTOBJEXT); \
	  rm -f $(localedir)/$$lang/LC_MESSAGES/$(PACKAGE)$(INSTOBJEXT).m; \
	  rm -f $(gnulocaledir)/$$lang/LC_MESSAGES/$(PACKAGE)$(INSTOBJEXT); \
	  rm -f $(gnulocaledir)/$$lang/LC_MESSAGES/$(PACKAGE)$(INSTOBJEXT).m; \
	done
	rm -f $(gettextsrcdir)/po-Makefile.in.in

check: all

cat-id-tbl.o: $(srcdir)/cat-id-tbl.c $(top_srcdir)/intl/libgettext.h
	$(COMPILE) $(srcdir)/cat-id-tbl.c

dvi info tags TAGS ID:

mostlyclean:
	rm -f core core.* *.pox $(PACKAGE).po *.old.po cat-id-tbl.tmp
	rm -fr *.o

clean: mostlyclean

distclean: clean
	rm -f Makefile Makefile.in POTFILES *.mo *.msg *.cat *.cat.m

maintainer-clean: distclean
	@echo "This command is intended for maintainers to use;"
	@echo "it deletes files that may require special tools to rebuild."
	rm -f $(GMOFILES) cat-id-tbl.c stamp-cat-id

distdir = ../$(PACKAGE)-$(VERSION)/$(subdir)
dist distdir: update-po $(DISTFILES)
	dists="$(DISTFILES)"; \
	for file in $$dists; do \
	  ln $(srcdir)/$$file $(distdir) 2> /dev/null \
	    || cp -p $(srcdir)/$$file $(distdir); \
	done

update-po: Makefile
	$(MAKE) $(srcdir)/$(PACKAGE).pot
	PATH=`pwd`/../src:$$PATH; \
	cd $(srcdir); \
	catalogs='$(CATALOGS)'; \
	for cat in $$catalogs; do \
	  cat=`basename $$cat`; \
	  lang=`echo $$cat | sed 's/\$(CATOBJEXT)$$//'`; \
	  mv $$lang.po $$lang.old.po; \
	  echo "$$lang:"; \
	  if $(MSGMERGE) $$lang.old.po $(PACKAGE).pot -o $$lang.po; then \
	    rm -f $$lang.old.po; \
	  else \
	    echo "msgmerge for $$cat failed!"; \
	    rm -f $$lang.po; \
	    mv $$lang.old.po $$lang.po; \
	  fi; \
	done

POTFILES: POTFILES.in
	( if test 'x$(srcdir)' != 'x.'; then \
	    posrcprefix='$(top_srcdir)/'; \
	  else \
	    posrcprefix="../"; \
	  fi; \
	  rm -f $@-t $@ \
	    && (sed -e '/^#/d' -e '/^[ 	]*$$/d' \
		    -e "s@.*@	$$posrcprefix& \\\\@" < $(srcdir)/$@.in \
		| sed -e '$$s/\\$$//') > $@-t \
	    && chmod a-w $@-t \
	    && mv $@-t $@ )

Makefile: Makefile.in.in ../config.status POTFILES
	cd .. \
	  && CONFIG_FILES=$(subdir)/$@.in CONFIG_HEADERS= \
	       $(SHELL) ./config.status

# Tell versions [3.59,3.63) of GNU make not to export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
