#!/bin/csh -f
#
#
#
# Script to create : Stand Alone Verilog-XL
#
#        set a=`sh -c "type cc"`
#        if ( "$a" == "cc is /usr/ucb/cc" ) then
#	echo "which cc" returned "/usr/ucb/cc"
#	echo This compiler will not yield a good executable.
#	echo Please adjust your PATH environment variable to pick up the Sun C Compiler.
#	exit 1
#	endif
set verbose
#
#
# The following line(s) will pre-compile your
# PLI C source files before the linking step.
#
/usr/gnu/bin/sparc-sun-solaris2.4-gcc -c -O \
    -DJEDA=jeda \ 
   ../../veriuser/veriuser.c \
   -I/usr/cadence/LDV3.3/tools/verilog/include

/usr/gnu/bin/sparc-sun-solaris2.4-gcc -c -O \
   /usr/cadence/LDV3.3/tools/verilog/src/vpi_user.c \
   -I/usr/cadence/LDV3.3/tools/verilog/include
# The following is the actual compile/link
# statement:                              
#                                         
/usr/gnu/bin/sparc-sun-solaris2.4-gcc  -o verilog \
   /usr/cadence/LDV3.3/tools/verilog/lib/vlog.o \
 /usr/cadence/LDV3.3/tools/verilog/lib/libdlc.a \
   -L/usr/cadence/LDV3.3/tools/lib \
   /usr/cadence/LDV3.3/tools/verilog/lib/omnitasks.o \
   veriuser.o \
   vpi_user.o \
   $JEDA_HOME/lib/jeda_pli.o \
   -lcla_sh \
   -lcdsCommon_sh \
   -I/usr/cadence/LDV3.3/tools/verilog/include \
   -L/usr/cadence/LDV3.3/tools/verilog/lib \
   -lnewsdfa \
   -lsdfi \
   -lvoids \
-lsocket -lnsl -lm -ldl -lw -lgen -lintl 
#
unset verbose
