%token <keyword> JDT_abstract
%token <keyword> JDT_advice
%token <keyword> JDT_array
%token <keyword> JDT_aspect
%token <keyword> JDT_assoc
%token <keyword> JDT_bit
%token <keyword> JDT_bothedge
%token <keyword> JDT_break
%token <keyword> JDT_breakpoint
%token <keyword> JDT_call
%token <keyword> JDT_case
%token <keyword> JDT_casex
%token <keyword> JDT_casez
%token <keyword> JDT_class
%token <keyword> JDT_class_type
%token <keyword> JDT_clone
%token <keyword> JDT_connectionset
%token <keyword> JDT_continue
%token <keyword> JDT_default
%token <keyword> JDT_depth
%token <keyword> JDT_do
%token <keyword> JDT_double
%token <keyword> JDT_drive
%token <keyword> JDT_else
%token <keyword> JDT_enum
%token <keyword> JDT_export
%token <keyword> JDT_extends
%token <keyword> JDT_extern
%token <keyword> JDT_false
%token <keyword> JDT_final
%token <keyword> JDT_float
%token <keyword> JDT_for
%token <keyword> JDT_forever
%token <keyword> JDT_fork
%token <keyword> JDT_global
%token <keyword> JDT_if
%token <keyword> JDT_initial
%token <keyword> JDT_inout
%token <keyword> JDT_input
%token <keyword> JDT_int
%token <keyword> JDT_join
%token <keyword> JDT_knife
%token <keyword> JDT_list
%token <keyword> JDT_local
%token <keyword> JDT_long
%token <keyword> JDT_marray
%token <keyword> JDT_negedge
%token <keyword> JDT_new
%token <keyword> JDT_node
%token <keyword> JDT_null
%token <keyword> JDT_output
%token <keyword> JDT_overwrite
%token <keyword> JDT_p_and
%token <keyword> JDT_p_or
%token <keyword> JDT_port
%token <keyword> JDT_portset
%token <keyword> JDT_posedge
%token <keyword> JDT_protected
%token <keyword> JDT_randcase
%token <keyword> JDT_repeat
%token <keyword> JDT_return
%token <keyword> JDT_sample
%token <keyword> JDT_signal
%token <keyword> JDT_skew
%token <keyword> JDT_spoon
%token <keyword> JDT_static
%token <keyword> JDT_string
%token <keyword> JDT_stridx
%token <keyword> JDT_strong
%token <keyword> JDT_super
%token <keyword> JDT_teminate
%token <keyword> JDT_terminate
%token <keyword> JDT_this
%token <keyword> JDT_true
%token <keyword> JDT_typedef
%token <keyword> JDT_var
%token <keyword> JDT_verilog
%token <keyword> JDT_void
%token <keyword> JDT_weak
%token <keyword> JDT_while
%token <keyword> JDT_RND
%token <keyword> JDT_CYC
