%token <keyword> VI_Qeqeq
%token <keyword> VI_abstract
%token <keyword> VI_aspect
%token <keyword> VI_advice
%token <keyword> VI_advice_end
%token <keyword> VI_afunc
%token <keyword> VI_alloc
%token <keyword> VI_alloc_func
%token <keyword> VI_alloc_static
%token <keyword> VI_alu
%token <keyword> VI_and
%token <keyword> VI_arg
%token <keyword> VI_array
%token <keyword> VI_assoc
%token <keyword> VI_bit
%token <keyword> VI_bothedge
%token <keyword> VI_breakpoint
%token <keyword> VI_call
%token <keyword> VI_call_m
%token <keyword> VI_call_a
%token <keyword> VI_call_advice
%token <keyword> VI_cancel
%token <keyword> VI_chk_overwrite
%token <keyword> VI_class
%token <keyword> VI_class_alloc
%token <keyword> VI_class_alloc_end
%token <keyword> VI_class_initial_begin
%token <keyword> VI_class_initial_end
%token <keyword> VI_class_type
%token <keyword> VI_clk_of_port
%token <keyword> VI_clk_of_pset_port
%token <keyword> VI_clk_of_signal
%token <keyword> VI_clone
%token <keyword> VI_cmp
%token <keyword> VI_cmpx
%token <keyword> VI_cmpz
%token <keyword> VI_concat
%token <keyword> VI_connection
%token <keyword> VI_copy
%token <keyword> VI_copy_obj
%token <keyword> VI_convert
%token <keyword> VI_dec
%token <keyword> VI_depth
%token <keyword> VI_div
%token <keyword> VI_double
%token <keyword> VI_drive
%token <keyword> VI_dup
%token <keyword> VI_duplicate
%token <keyword> VI_enter_advice
%token <keyword> VI_enum
%token <keyword> VI_eor
%token <keyword> VI_eqQeq
%token <keyword> VI_eqeq
%token <keyword> VI_eqeqQ
%token <keyword> VI_eqeqeq
%token <keyword> VI_eqCeq
%token <keyword> VI_Qne
%token <keyword> VI_error
%token <keyword> VI_exec
%token <keyword> VI_exit
%token <keyword> VI_export
%token <keyword> VI_extends
%token <keyword> VI_extern
%token <keyword> VI_final
%token <keyword> VI_float
%token <keyword> VI_fork
%token <keyword> VI_formal
%token <keyword> VI_func
%token <keyword> VI_function
%token <keyword> VI_func_end
%token <keyword> VI_ge
%token <keyword> VI_gen_child
%token <keyword> VI_gen_frame
%token <keyword> VI_gen_m_frame
%token <keyword> VI_gen_a_frame
%token <keyword> VI_get_this
%token <keyword> VI_get_sig_subbit
%token <keyword> VI_get_subbit
%token <keyword> VI_get_super
%token <keyword> VI_get_child
%token <keyword> VI_get_return
%token <keyword> VI_global
%token <keyword> VI_gt
%token <keyword> VI_i_endian
%token <keyword> VI_inc
%token <keyword> VI_input
%token <keyword> VI_inout
%token <keyword> VI_initial_begin
%token <keyword> VI_initial_end
%token <keyword> VI_initial_init
%token <keyword> VI_int
%token <keyword> VI_jedacmp
%token <keyword> VI_jmp
%token <keyword> VI_jnz
%token <keyword> VI_join
%token <keyword> VI_jz
%token <keyword> VI_knife
%token <keyword> VI_le
%token <keyword> VI_leaf
%token <keyword> VI_list
%token <keyword> VI_load_const
%token <keyword> VI_load_one
%token <keyword> VI_load_port
%token <keyword> VI_load_port_ptr
%token <keyword> VI_load_pset_port
%token <keyword> VI_load_pset_port_ptr
%token <keyword> VI_load_sig_pt
%token <keyword> VI_load_static
%token <keyword> VI_load_super
%token <keyword> VI_load_this
%token <keyword> VI_load_thread
%token <keyword> VI_load_zero
%token <keyword> VI_loadg
%token <keyword> VI_loadl
%token <keyword> VI_loadm
%token <keyword> VI_local
%token <keyword> VI_long
%token <keyword> VI_lshift
%token <keyword> VI_lt
%token <keyword> VI_lvar
%token <keyword> VI_marray
%token <keyword> VI_member_signal
%token <keyword> VI_mfunc
%token <keyword> VI_minus
%token <keyword> VI_mod
%token <keyword> VI_nand
%token <keyword> VI_ne
%token <keyword> VI_negedge
%token <keyword> VI_neor
%token <keyword> VI_neqeq
%token <keyword> VI_new
%token <keyword> VI_new_obj
%token <keyword> VI_noedge
%token <keyword> VI_nor
%token <keyword> VI_normal
%token <keyword> VI_null
%token <keyword> VI_nz_lsb
%token <keyword> VI_obj
%token <keyword> VI_or
%token <keyword> VI_output
%token <keyword> VI_overwrite
%token <keyword> VI_p_and
%token <keyword> VI_p_or
%token <keyword> VI_path
%token <keyword> VI_plus
%token <keyword> VI_pop
%token <keyword> VI_pop_this
%token <keyword> VI_port
%token <keyword> VI_portset
%token <keyword> VI_posedge
%token <keyword> VI_protected
%token <keyword> VI_pset_port
%token <keyword> VI_ptset
%token <keyword> VI_push
%token <keyword> VI_restore_acc
%token <keyword> VI_return
%token <keyword> VI_return_advice
%token <keyword> VI_return_l
%token <keyword> VI_return_n
%token <keyword> VI_rshift
%token <keyword> VI_sample
%token <keyword> VI_save_acc
%token <keyword> VI_signal
%token <keyword> VI_single
%token <keyword> VI_skew
%token <keyword> VI_spoon
%token <keyword> VI_stat_var
%token <keyword> VI_static
%token <keyword> VI_static_init
%token <keyword> VI_static_init_end
%token <keyword> VI_store_adjust
%token <keyword> VI_store_obj
%token <keyword> VI_store_port
%token <keyword> VI_store_pset_port
%token <keyword> VI_store_sig_g
%token <keyword> VI_store_sig_l
%token <keyword> VI_store_sig_m
%token <keyword> VI_store_sig_static
%token <keyword> VI_store_static
%token <keyword> VI_storeg
%token <keyword> VI_storel
%token <keyword> VI_storem
%token <keyword> VI_stridx
%token <keyword> VI_string
%token <keyword> VI_strong
%token <keyword> VI_subbit
%token <keyword> VI_sync
%token <keyword> VI_sys_class
%token <keyword> VI_terminate
%token <keyword> VI_times
%token <keyword> VI_to_int
%token <keyword> VI_u_and
%token <keyword> VI_u_eor
%token <keyword> VI_u_minus
%token <keyword> VI_u_nand
%token <keyword> VI_u_neor
%token <keyword> VI_u_nor
%token <keyword> VI_u_not
%token <keyword> VI_u_or
%token <keyword> VI_u_tilde
%token <keyword> VI_urshift
%token <keyword> VI_var
%token <keyword> VI_variable
%token <keyword> VI_veri_call
%token <keyword> VI_verilog_task
%token <keyword> VI_void
%token <keyword> VI_weak
