/********************************************/
/* header generated by gen_header.pl        */
/********************************************/
void  JD_exec_i_lt_i() ;
void  JD_exec_i_gt_i() ;
void  JD_exec_i_eqeq_i() ;
void  JD_exec_i_le_i() ;
void  JD_exec_i_ge_i() ;
void  JD_exec_i_ne_i() ;
void  JD_exec_i_eqeqeq_i() ;
void  JD_exec_i_neqeq_i() ;
void  JD_exec_i_eqQeq_i() ;
void  JD_exec_i_eqeqQ_i() ;
void  JD_exec_i_Qeqeq_i() ;
void  JD_exec_i_Qne_i() ;
void  JD_exec_i_minus_i() ;
void  JD_exec_i_plus_i() ;
void  JD_exec_i_times_i() ;
void  JD_exec_i_div_i() ;
void  JD_exec_i_mod_i() ;
void  JD_exec_i_and_i() ;
void  JD_exec_i_or_i() ;
void  JD_exec_i_eor_i() ;
void  JD_exec_i_nand_i() ;
void  JD_exec_i_NOR_i() ;
void  JD_exec_i_neor_i() ;
void  JD_exec_u_minus_i() ;
void  JD_exec_u_tilde_i() ;
void  JD_exec_u_not_i() ;
void  JD_exec_u_and_i() ;
void  JD_exec_u_or_i() ;
void  JD_exec_u_eor_i() ;
void  JD_exec_u_nand_i() ;
void  JD_exec_u_nor_i() ;
void  JD_exec_u_neor_i() ;
