/********************************************/
/* header generated by gen_header.pl        */
/********************************************/
void  JD_exec_f_lt_f() ;
void  JD_exec_f_gt_f() ;
void  JD_exec_f_eqeq_f() ;
void  JD_exec_f_le_f() ;
void  JD_exec_f_ge_f() ;
void  JD_exec_f_ne_f() ;
void  JD_exec_f_eqeqeq_f() ;
void  JD_exec_f_neqeq_f() ;
void  JD_exec_f_eqQeq_f() ;
void  JD_exec_f_eqeqQ_f() ;
void  JD_exec_f_Qeqeq_f() ;
void  JD_exec_f_minus_f() ;
void  JD_exec_f_plus_f() ;
void  JD_exec_f_times_f() ;
void  JD_exec_f_div_f() ;
void  JD_exec_f_mod_f() ;
void  JD_exec_u_minus_f() ;
void  JD_exec_u_tilde_f() ;
void  JD_exec_u_not_f() ;
void  JD_exec_m_lt_m() ;
void  JD_exec_m_gt_m() ;
void  JD_exec_m_eqeq_m() ;
void  JD_exec_m_le_m() ;
void  JD_exec_m_ge_m() ;
void  JD_exec_m_ne_m() ;
void  JD_exec_m_eqeqeq_m() ;
void  JD_exec_m_neqeq_m() ;
void  JD_exec_m_eqQeq_m() ;
void  JD_exec_m_eqeqQ_m() ;
void  JD_exec_m_Qeqeq_m() ;
void  JD_exec_m_minus_m() ;
void  JD_exec_m_plus_m() ;
void  JD_exec_m_times_m() ;
void  JD_exec_m_div_m() ;
void  JD_exec_m_mod_m() ;
