/********************************************/
/* macro generated by gen_code_out_macro_prod.pl */
/********************************************/
#  define CALL_EXEC_F_LT_F  JD_exec_f_lt_f()
#define OUT_EXEC_F_LT_F \
    OUT0( "JD_exec_f_lt_f() ;\n" ) ; 
#  define CALL_EXEC_F_GT_F  JD_exec_f_gt_f()
#define OUT_EXEC_F_GT_F \
    OUT0( "JD_exec_f_gt_f() ;\n" ) ; 
#  define CALL_EXEC_F_EQEQ_F  JD_exec_f_eqeq_f()
#define OUT_EXEC_F_EQEQ_F \
    OUT0( "JD_exec_f_eqeq_f() ;\n" ) ; 
#  define CALL_EXEC_F_LE_F  JD_exec_f_le_f()
#define OUT_EXEC_F_LE_F \
    OUT0( "JD_exec_f_le_f() ;\n" ) ; 
#  define CALL_EXEC_F_GE_F  JD_exec_f_ge_f()
#define OUT_EXEC_F_GE_F \
    OUT0( "JD_exec_f_ge_f() ;\n" ) ; 
#  define CALL_EXEC_F_NE_F  JD_exec_f_ne_f()
#define OUT_EXEC_F_NE_F \
    OUT0( "JD_exec_f_ne_f() ;\n" ) ; 
#  define CALL_EXEC_F_EQEQEQ_F  JD_exec_f_eqeqeq_f()
#define OUT_EXEC_F_EQEQEQ_F \
    OUT0( "JD_exec_f_eqeqeq_f() ;\n" ) ; 
#  define CALL_EXEC_F_NEQEQ_F  JD_exec_f_neqeq_f()
#define OUT_EXEC_F_NEQEQ_F \
    OUT0( "JD_exec_f_neqeq_f() ;\n" ) ; 
#  define CALL_EXEC_F_EQQEQ_F  JD_exec_f_eqQeq_f()
#define OUT_EXEC_F_EQQEQ_F \
    OUT0( "JD_exec_f_eqQeq_f() ;\n" ) ; 
#  define CALL_EXEC_F_EQEQQ_F  JD_exec_f_eqeqQ_f()
#define OUT_EXEC_F_EQEQQ_F \
    OUT0( "JD_exec_f_eqeqQ_f() ;\n" ) ; 
#  define CALL_EXEC_F_QEQEQ_F  JD_exec_f_Qeqeq_f()
#define OUT_EXEC_F_QEQEQ_F \
    OUT0( "JD_exec_f_Qeqeq_f() ;\n" ) ; 
#  define CALL_EXEC_F_MINUS_F  JD_exec_f_minus_f()
#define OUT_EXEC_F_MINUS_F \
    OUT0( "JD_exec_f_minus_f() ;\n" ) ; 
#  define CALL_EXEC_F_PLUS_F  JD_exec_f_plus_f()
#define OUT_EXEC_F_PLUS_F \
    OUT0( "JD_exec_f_plus_f() ;\n" ) ; 
#  define CALL_EXEC_F_TIMES_F  JD_exec_f_times_f()
#define OUT_EXEC_F_TIMES_F \
    OUT0( "JD_exec_f_times_f() ;\n" ) ; 
#  define CALL_EXEC_F_DIV_F  JD_exec_f_div_f()
#define OUT_EXEC_F_DIV_F \
    OUT0( "JD_exec_f_div_f() ;\n" ) ; 
#  define CALL_EXEC_F_MOD_F  JD_exec_f_mod_f()
#define OUT_EXEC_F_MOD_F \
    OUT0( "JD_exec_f_mod_f() ;\n" ) ; 
#  define CALL_EXEC_U_MINUS_F  JD_exec_u_minus_f()
#define OUT_EXEC_U_MINUS_F \
    OUT0( "JD_exec_u_minus_f() ;\n" ) ; 
#  define CALL_EXEC_U_TILDE_F  JD_exec_u_tilde_f()
#define OUT_EXEC_U_TILDE_F \
    OUT0( "JD_exec_u_tilde_f() ;\n" ) ; 
#  define CALL_EXEC_U_NOT_F  JD_exec_u_not_f()
#define OUT_EXEC_U_NOT_F \
    OUT0( "JD_exec_u_not_f() ;\n" ) ; 
#  define CALL_EXEC_M_LT_M  JD_exec_m_lt_m()
#define OUT_EXEC_M_LT_M \
    OUT0( "JD_exec_m_lt_m() ;\n" ) ; 
#  define CALL_EXEC_M_GT_M  JD_exec_m_gt_m()
#define OUT_EXEC_M_GT_M \
    OUT0( "JD_exec_m_gt_m() ;\n" ) ; 
#  define CALL_EXEC_M_EQEQ_M  JD_exec_m_eqeq_m()
#define OUT_EXEC_M_EQEQ_M \
    OUT0( "JD_exec_m_eqeq_m() ;\n" ) ; 
#  define CALL_EXEC_M_LE_M  JD_exec_m_le_m()
#define OUT_EXEC_M_LE_M \
    OUT0( "JD_exec_m_le_m() ;\n" ) ; 
#  define CALL_EXEC_M_GE_M  JD_exec_m_ge_m()
#define OUT_EXEC_M_GE_M \
    OUT0( "JD_exec_m_ge_m() ;\n" ) ; 
#  define CALL_EXEC_M_NE_M  JD_exec_m_ne_m()
#define OUT_EXEC_M_NE_M \
    OUT0( "JD_exec_m_ne_m() ;\n" ) ; 
#  define CALL_EXEC_M_EQEQEQ_M  JD_exec_m_eqeqeq_m()
#define OUT_EXEC_M_EQEQEQ_M \
    OUT0( "JD_exec_m_eqeqeq_m() ;\n" ) ; 
#  define CALL_EXEC_M_NEQEQ_M  JD_exec_m_neqeq_m()
#define OUT_EXEC_M_NEQEQ_M \
    OUT0( "JD_exec_m_neqeq_m() ;\n" ) ; 
#  define CALL_EXEC_M_EQQEQ_M  JD_exec_m_eqQeq_m()
#define OUT_EXEC_M_EQQEQ_M \
    OUT0( "JD_exec_m_eqQeq_m() ;\n" ) ; 
#  define CALL_EXEC_M_EQEQQ_M  JD_exec_m_eqeqQ_m()
#define OUT_EXEC_M_EQEQQ_M \
    OUT0( "JD_exec_m_eqeqQ_m() ;\n" ) ; 
#  define CALL_EXEC_M_QEQEQ_M  JD_exec_m_Qeqeq_m()
#define OUT_EXEC_M_QEQEQ_M \
    OUT0( "JD_exec_m_Qeqeq_m() ;\n" ) ; 
#  define CALL_EXEC_M_MINUS_M  JD_exec_m_minus_m()
#define OUT_EXEC_M_MINUS_M \
    OUT0( "JD_exec_m_minus_m() ;\n" ) ; 
#  define CALL_EXEC_M_PLUS_M  JD_exec_m_plus_m()
#define OUT_EXEC_M_PLUS_M \
    OUT0( "JD_exec_m_plus_m() ;\n" ) ; 
#  define CALL_EXEC_M_TIMES_M  JD_exec_m_times_m()
#define OUT_EXEC_M_TIMES_M \
    OUT0( "JD_exec_m_times_m() ;\n" ) ; 
#  define CALL_EXEC_M_DIV_M  JD_exec_m_div_m()
#define OUT_EXEC_M_DIV_M \
    OUT0( "JD_exec_m_div_m() ;\n" ) ; 
#  define CALL_EXEC_M_MOD_M  JD_exec_m_mod_m()
#define OUT_EXEC_M_MOD_M \
    OUT0( "JD_exec_m_mod_m() ;\n" ) ; 
